cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>/', views.add_to_cart, name='add_to_cart'),
    path('modify/<item_id>/', views.modify_cart, name='modify_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ContactFormSubmitView.as_view(), name='contactform'),
    path('form-submissions/',
         views.ContactView.as_view(), name='contact-submissions'),
    path('success/', views.contact_success, name='contact-success'),
]

flame_masters/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
    # setting the static so django can see the media files
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'flame_masters.views.handler404'
handler403 = 'flame_masters.views.handler403'
handler500 = 'flame_masters.views.handler500'

contact/models.py
from django.db import models


class Contact(models.Model):
    """
    A model to store contact form entries
    """
    Q_CHOICES = (
        ('general_query', 'General Query'),
        ('return', 'Return'),
        ('complaint', 'Complaint'),
    )

    # The type of query from the user
    reason = models.CharField(max_length=14, choices=Q_CHOICES)
    order_number = models.CharField(max_length=50, null=True, blank=True)
    name = models.CharField(max_length=30, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    message = models.TextField(null=False, blank=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        # order the contact form posts on when they were created
        # newest first
        ordering = ['-created_on']

    def __str__(self):
        return self.email

contact/forms.py
from django.forms import ModelForm
from .models import Contact
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit, Reset


class ContactForm(ModelForm):
    """
    A modelform from the Contact model
    For the user to enter their queries
    """
    class Meta:
        model = Contact
        fields = [
            'reason',
            'order_number',
            'name',
            'email',
            'message',
        ]

    def __init__(self, *args, **kwargs):
        # crispy forms helper and layouts
        super(ContactForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_action = 'contactform'
        self.helper.layout = Layout(
            Field('reason'),
            Field('order_number',
                  placeholder='If applicable, add your order number'),
            Field('name'),
            Field('email'),
            Field('message', placeholder="How can we help?"),
            Reset('reset',
                  'Reset Form',
                  css_class='btn btn-outline-black rounded-0 text-uppercase'),
            Submit('submit',
                   'Submit!',
                   css_class='btn btn-black rounded-0 text-uppercase'),
        )

contact/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Contact
from .forms import ContactForm


class ContactFormSubmitView(CreateView):
    """
    CreateView to submit a new contact form submission.
    This allows users to submit general queries, complaints or
    return queries
    """
    model = Contact
    template_name = 'contact/contact.html'
    form_class = ContactForm
    # redirect the user to the contact-success page
    success_url = reverse_lazy('contact-success')

    def form_valid(self, form):
        messages.success(self.request, 'Successfully added your Query!')
        return super().form_valid(form)


def contact_success(request):
    """
    A view for redirecting the user to a thank you page
    after submitting a query on the contact form
    """
    return render(request, 'contact/contact_success.html')


class ContactView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    """
    ListView to allow the admin user to view
    the contact form submissions on the front end
    """

    model = Contact
    queryset = Contact.objects.order_by('-created_on')
    template_name = 'contact/contact_submissions.html'
    context_object_name = 'contact_list'

    def test_func(self):
        """
        Method to only allow superuser access to the view
        https://docs.djangoproject.com/en/5.0/topics/auth/default/#django.contrib.auth.mixins.UserPassesTestMixin
        """
        if self.request.user.is_superuser:
            return True
        return False

contact/templates/contact/contact.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container">
    <div class="row">
        <div class="col">
            <hr>
            <h2 class="logo-font mb-4">Contact Us</h2>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-lg-6 mb-5">
            <!-- crispy forms contact form -->
            {% csrf_token %}
            {% crispy form %}
        </div>
        <div class="col-12 col-lg-6 col-sm-4 mb-5 order-lg-last">
            <!-- MailChimp newsletter signup -->
            <div id="mc_embed_shell">
                <div id="mc_embed_signup">
                    <form
                        action="https://herokuapp.us21.list-manage.com/subscribe/post?u=f7f1b996faf0a276307ded4ba&amp;id=c561fda60b&amp;f_id=0085fae6f0"
                        method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate"
                        target="_blank">
                        <div id="mc_embed_signup_scroll">
                            <h2>Subscribe to our Newsletter</h2>
                            <div class="mc-field-group"><label for="mce-EMAIL">Email Address <span
                                        class="asterisk">*</span></label><input type="email" name="EMAIL"
                                    class="required email" id="mce-EMAIL" required="" value=""></div>
                            <div id="mce-responses" class="clear foot">
                                <div class="response" id="mce-error-response" style="display: none;"></div>
                                <div class="response" id="mce-success-response" style="display: none;"></div>
                            </div>
                            <div aria-hidden="true" style="position: absolute; left: -5000px;">
                                /* real people should not fill this in and expect good things - do not remove this or
                                risk form bot signups */
                                <input type="text" name="b_f7f1b996faf0a276307ded4ba_c561fda60b" tabindex="-1" value="">
                            </div>
                            <div class="optionalParent">
                                <div class="clear foot">
                                    <input type="submit" name="subscribe" id="mc-embedded-subscribe" class="button"
                                        value="Subscribe">
                                    <p style="margin: 0px auto;"><a href="http://eepurl.com/iHMuOg"
                                            title="Mailchimp - email marketing made easy and fun"><span
                                                style="display: inline-block; background-color: transparent; border-radius: 4px;"><img
                                                    class="refferal_badge"
                                                    src="https://digitalasset.intuit.com/render/content/dam/intuit/mc-fe/en_us/images/intuit-mc-rewards-text-dark.svg"
                                                    alt="Intuit Mailchimp"
                                                    style="width: 220px; height: 40px; display: flex; padding: 2px 0px; justify-content: center; align-items: center;"></span></a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %}

contact/templates/contact/contact_submissions.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="logo-font mb-4">Contact Form Submissions</h2>
                <hr>
            </div>
        </div>
        
        {% for contact in contact_list %}
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ contact.name }}</h5>
                        <p class="card-text"><strong>Email:</strong> {{ contact.email }}</p>
                        <p class="card-text"><strong>Date:</strong> {{ contact.created_on }}</p>
                        <p class="card-text"><strong>Contact Reason: </strong>{{ contact.get_reason_display }}</p>
                        {% if contact.order_number %}
                        <p class="card-text"><strong>Order Number:</strong> {{ contact.order_number }}</p>
                        {% endif %}
                        <p class="card-text"><strong>Message:</strong> {{ contact.message }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

contact/templates/contact/contact_success.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col">
                <hr>
                <h2 class="logo-font mb-4">Thank You</h2>
                <hr>
            </div>
        </div>

        <div class="row">
            <!-- Thank the user for their contact -->
            <div class="col-12 col-lg-7">
                <p>
                    Thank you for contacting FlameMasters!
                </p>
                <p>
                    Our team will be in touch with you as soon as possible
                </p>
            </div>
        </div>
    </div>
{% endblock %}